name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y bats shellcheck tar gzip

      - name: Run lint & tests
        run: |
          bash ci/lint.sh
          bash ci/test.sh

      - name: Build binaries
        run: bash ci/build.sh

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
